### ISSUE TITLE
Add Support for Archer A8(EU) Router device

### ISSUE THREAD

**Issue by Gipssik** [piekstra/tplink-cloud-api#65]
I get TypeError every time I use some functions that are coroutines.

### Configuration:

* Debian 11, WSL2
* Python 3.10.3
* tplink-cloud-api 4.1.3

### Code:

    import asyncio
    import os
    
    from dotenv import load_dotenv
    from tplinkcloud import TPLinkDeviceManager
    from tplinkcloud.device import TPLinkDevice
    
    load_dotenv()
    username = os.getenv("USERNAME")
    password = os.getenv("PASSWORD")
    device_manager = TPLinkDeviceManager(username, password)
    
    
    async def main():
        device: TPLinkDevice = await device_manager.find_device("Archer A8")
        print(await device.toggle())
    
    
    if __name__ == "__main__":
        asyncio.run(main())

### Traceback:

    Traceback (most recent call last):
      File "/path/to/project/router/main.py", line 20, in <module>
        asyncio.run(main())
      File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)
      File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/path/to/project/router/main.py", line 16, in main
        print(await device.toggle())
      File "/path/to/project/router/venv/lib/python3.10/site-packages/tplinkcloud/device.py", line 83, in toggle
        if await self.is_on():
      File "/path/to/project/router/venv/lib/python3.10/site-packages/tplinkcloud/device.py", line 97, in is_on
        device_sys_info = await self.get_sys_info()
      File "/path/to/project/router/venv/lib/python3.10/site-packages/tplinkcloud/device.py", line 94, in get_sys_info
        return await self._get_sys_info()
      File "/path/to/project/router/venv/lib/python3.10/site-packages/tplinkcloud/device.py", line 89, in _get_sys_info
        return await self._pass_through_request('system', 'get_sysinfo', None)
      File "/path/to/project/router/venv/lib/python3.10/site-packages/tplinkcloud/device.py", line 62, in _pass_through_request
        response = await self._client.pass_through_request(
      File "/path/to/project/router/venv/lib/python3.10/site-packages/tplinkcloud/device_client.py", line 65, in pass_through_request
        return json.loads(response.result.get('responseData'))
      File "/usr/local/lib/python3.10/json/__init__.py", line 339, in loads
        raise TypeError(f'the JSON object must be str, bytes or bytearray, '
    TypeError: the JSON object must be str, bytes or bytearray, not dict
    
    Process finished with exit code 1

## UPD

I started to debug it and found some strange places and the cause of exception I guess.

`request_data` at `line 53, file device.py` looks strange:

![image](https://user-images.githubusercontent.com/75203753/170733900-9d49fc89-5092-4a3d-a0ef-8598f76f1ad7.png)

And the cause of exception at `line 36, file device_client.py`:

![image](https://user-images.githubusercontent.com/75203753/170734345-663dd56c-94ec-4228-a90b-bd387e7d5899.png)

**Comment by piekstra** [comment]
@Gipssik what model of device are you trying to find? I wonder if this is an issue with compatibility of the library.

**Comment by Gipssik** [comment]
@piekstra I'm trying to find my router Archer A8(EU), it's connected to my Tether app. The library finds it and I can get its `device_info`

**Comment by piekstra** [comment]
> @piekstra I'm trying to find my router Archer A8(EU), it's connected to my Tether app. The library finds it and I can get its `device_info`

Ahhh that explains it. While this library works with the TP-Link API, it's currently only written to support certain TP-Link Kasa devices. At this time, any other devices are unlikely to be properly accessed via this library. To add support for your device would be a matter of reverse engineering the Tether app or monitoring its network requests and figuring out the API contracts since they are not officially documented.

**Comment by GuyKh** [comment]
@piekstra I'm now trying to do exactly this;

I've tried running MITM on TPLink Tether app (HTTP toolkit) - but it fails for "no internet" when I try to log in.
Can you share on how did you reverse engineer the API requests?

**Comment by piekstra** [comment]
> [@piekstra](https://github.com/piekstra) I'm now trying to do exactly this;
> 
> I've tried running MITM on TPLink Tether app (HTTP toolkit) - but it fails for "no internet" when I try to log in. Can you share on how did you reverse engineer the API requests?

Hi @GuyKh so, not sure if you are on iOS or Android but the easiest route is actually to decompile the Android app (APK) and inspect the source code for endpoints and request models.

**Comment by GuyKh** [comment]
@piekstra I'm using android.
Any tips on tools or the process of decompiling?

**Comment by piekstra** [comment]
@GuyKh yes! I created some guides on the process - they may not be entirely accurate as you would be the first consumer apart from myself.

Wiki is here: https://github.com/piekstra/tplink-cloud-api/wiki

And here's the process I used for the Kasa app: https://github.com/piekstra/tplink-cloud-api/wiki/APK-Decompilation-Guide

**Comment by piekstra** [comment]
@GuyKh and if you're familiar with tools like Codex or Claude Code, point them to this issue thread and explain that you're trying to do similar and it should figure it out pretty well!
